grid-parity-exchange/Egret

egret/model_library/unit_commitment/status_vars.py
=> removing unneeded imports from status_vars

egret/model_library/transmission/branch.py, egret/models/acopf.py, egret/parsers/matpower_parser.py
Updated parser to handle inf and -inf datatypes in the pmin, pmax, qmin and qmax fields.
=> Updates for handling generator limits of type -inf/inf and line limits of type NoneType

.travis.yml, setup.py
I updated the setup.py file to find all submodules in egret so that ```python setup.py install``` works.
=> Fixing Install

egret/parsers/matpower_parser.py
pglib-opf has been updated to not have INF and NAN data in the input files.
=> Removed check for isnan, isinf

README.md, setup.py
Adding matplotlib and seaborn to setup.py, as they are dependencies of the newly added visualization code base.
=> Adding visualization library dependencies, fix typo in README.

egret/model_library/transmission/tx_utils.py, egret/models/unit_commitment.py
=> Adding headroom to solve_unit_commitment

egret/viz/generate_graphs.py
The prior implementation sorted the keys in every 'value' dictionary, which aren't necessarily the order of the time steps, which are uniquely specified in ModelData.data['system']['time_indices'].
This change ensures the times shown on the stack graph are in the same order as the times in the model, regardless of whether time_indices == time_indices.sorted().
=> tweaking timing in generate_graph

egret/models/dcopf.py, egret/models/dcopf_losses.py
The congestion (and losses) component of LMP is added to all the buses for each transmission line.
=> Bug fix for LMPs when using PTDF formulations of DCOPF

egret/common/lazy_ptdf_utils.py, egret/data/data_utils.py, egret/model_library/transmission/tx_calc.py, egret/models/dcopf.py, egret/models/dcopf_losses.py
I incorporated the core code to compute sparse PTDF; this should be easy to integrate into the lazy PTDF approach; the calculate_ptdf and calculate_ptdf_ldf functions in tx_calc.py take 1 extra field, "sparse_index_set_branch." This should tide us over until a code refactor can be completed!
=> sparse PTDF

egret/parsers/rts_gmlc_parser.py
This fixes two issues when parsing RTS-GMLC if using a filesystem that respects capitalization.
=> Capitalization issues in RTS-GMLC parser

egret/viz/generate_graphs.py
This PR makes the following enhancements to stackgraph generation:
1. Fills out fuel codes dictionary
1. Reserve shortfall now "covers" required reserve
1. Implicit reserves now calculated correctly when reserves are included
=> Minor fixes for stackgraph generation

egret/common/lazy_ptdf_utils.py, egret/model_library/unit_commitment/uc_model_generator.py, egret/models/dcopf.py, egret/models/dcopf_losses.py
=> Leaving user-supplied ptdf_options harmless

egret/viz/generate_graphs.py
* Implemented support for graphs with `show_individual_components == True`
* Refactored code for easier maintenance and added module-level variables for static definitions (hatching symbols)
* Changed aux fuel hatch symbol to just '..'
There are at least two dual fuel generators in case `tiny_uc_4` but only one of them at a time goes on auxiliary fuel.
=> Additional stack graph support for dual fuel generators

egret/common/lazy_ptdf_utils.py, egret/data/data_utils.py, egret/models/unit_commitment.py, egret/parsers/prescient_dat_parser.py
This enhances the lazy PTDF algorithm for unit commitment by adding two pieces of functionality:
1. Adds a "pre-LP phase", which finds a transmission feasible solution for a single time period and copies the active transmission constraints into every other time period.
1. Adds a "LP cleanup phase", which removes transmission constraints which are not binding after solving the LP relaxation but before starting the MIP.
=> Lazy PTDF Algorithm Enhancements

egret/model_library/unit_commitment/params.py
This makes a couple of fixes to the unit commitment data loader for a few previously uncovered edge cases.
=> Fix for no reference bus and no 'in_service' flag on load

egret/common/solver_interface.py, egret/model_library/unit_commitment/power_balance.py
...of models and PTDF matrices for advanced users.
=> Minor changes to help enable persistence

egret/common/solver_interface.py, egret/model_library/unit_commitment/power_balance.py, egret/models/acopf.py, egret/models/copperplate_dispatch.py, egret/models/dcopf.py, egret/models/dcopf_losses.py, egret/models/tests/test_unit_commitment.py, egret/models/unit_commitment.py, egret/viz/generate_graphs.py, egret/viz/tests/test_stack_graph.py
This PR allows users to pass arguments directly to the Pyomo solver's solve function through Egret.
=> Enabling solver_options

egret/model_library/transmission/branch.py, egret/model_library/transmission/bus.py, egret/models/ac_relaxations.py, egret/models/acopf.py, egret/models/tests/test_relaxations.py
This PR makes it easier to formulate various ACOPF relaxations. It also improves code reuse.
=> ACOPF and ACOPF Relaxations

.travis.yml, egret/model_library/transmission/branch.py, egret/models/acopf.py
This PR changes the polar ACOPF formulation to use a delta angle variable, which results in better relaxations.
=> ACOPF Relaxations

egret/model_library/transmission/tx_calc.py
Upstream changes to scipy require importing scipy.sparse. scipy.absolute is also being deprecated and has been replaced with numpy.absolute as recommended.
=> Modifying tx_calc for upstream changes to scipy

egret/common/solver_interface.py, egret/model_library/unit_commitment/params.py, egret/models/tests/test_unit_commitment.py, egret/parsers/prescient_dat_parser.py
This PR makes a few (admittedly) unrelated changes:
1. Updates to the unit commitment model and prescient dat parser for upstream changes
1. Enables the `FuelCost` attribute for prescient to be correctly interpreted
1. Restructures prescient dat parser to enable use with PySP
1. Adds xpress to the solver interface
=> Various minor updates

egret/models/ac_relaxations.py
=> expose slack flag

egret/model_library/unit_commitment/production_costs.py, egret/models/unit_commitment.py, egret/parsers/prescient_dat_parser.py
This PR does some slight refactoring of the unit commitment functionality of EGRET make its use by Prescient easier. Makes no changes to functionality.
=> Changes for easy Prescient integration

egret/models/unit_commitment.py
Closes #177; in support of https://github.com/grid-parity-exchange/Prescient/pull/62.
=> Reporting out prices in $/MWh for unit commitment and multiperiod dispatch

egret/viz/generate_graphs.py
- adding over-generation
- resolving warning from matplotlib
=> Modifications to stackgraph generation for Prescient

egret/models/ac_relaxations.py
the basic soc relaxation should not need Coramin
=> basic soc relaxation should not need coramin

egret/model_library/transmission/tx_utils.py
fix per unit scaling to scale q_load_mismatch_cost
=> fix penalty

egret/data/data_utils.py, egret/data/model_data.py, egret/data/tests/test_model_data.py, egret/models/tests/test_unit_commitment.py
=> Making ModelData.__init__ more useful

.github/workflows/egret.yml
This PR is trying to get some testing results even though ubuntu-latest is failing.
- Adding ubuntu-18.04 (but leaving ubuntu-latests so we continue to see the problem)
- Setting fail-fast to false so other test run even if ubuntu-latest fails
-
=> working on failed ubuntu test

egret/common/lazy_ptdf_utils.py
Egret's PTDF code currently incorrectly removes constraints from the Pyomo transmission blocks. Indexed constraints need to be removed from a Pyomo block by calling `del indexed_constr[key]`, not `del constraint_data`. This PR fixes this bug, which particularly causes issues when using a persistent solver and querying dual values for transmission limits.
=> Fixing bug in constraint removal

egret/common/lazy_ptdf_utils.py, egret/models/unit_commitment.py
Also fixes a bug introduced in #224.
=> Hooks for UC as subblock

setup.py
=> Setting up 0.5.0

setup.py
=> setting up 0.5.1; removing long description

setup.py
=> Setting up main for development

setup.py
Updating the required version of Coramin.
=> updating coramin version in requirements

setup.py
Prescient needs a version of Egret to release against.
-
-
=> Egret release 0.5.2

setup.py
=> Reset main for development

.github/workflows/egret.yml, .github/workflows/prescient.yml
=> Specify coramin version for GHA

egret/parsers/rts_gmlc/parser.py
=> Fixing refactoring issue

setup.py
See #290.
- Change pandas requirement to <1.5
-
=> Change to pandas<1.5 until #290 is fixed

.github/workflows/egret.yml
=> Fix failing windows tests

egret/model_library/unit_commitment/params.py
=> Fix copy+paste bug in power_generated_t0_validator.

egret/model_library/unit_commitment/params.py
=> Allow for negative fixed minimum production costs

setup.py
=> Egret release 0.5.3

.github/workflows/egret.yml
=> Add Python 3.10 & 3.11 to CI

egret/parsers/rts_gmlc/parser.py
Fixes parsing of RTS-GMLC files when using pandas 2.0.
Latest version of pandas dropped support for some date handling options in pd.read_csv().
-
-
=> Change how we read dates from files to keep up with changes to pandas

.github/workflows/publish-to-test-pypi.yml, setup.py
=> Update PyPI action

setup.py
=> Egret release 0.5.4

.github/workflows/publish-to-test-pypi.yml, setup.py
=> updating pypi publish

.github/workflows/egret.yml
=> Fix macos GHA

README.md
This PR adds a list of contributors along with their main contributions to the README. I'll need help getting the list of contributions correct. We should also consider adding more people to the list of contributors.
=> Add contributors to readme

.github/workflows/publish-to-test-pypi.yml
=> get publish to PyPI working again

.github/workflows/publish-to-test-pypi.yml, pyproject.toml
=> Getting Test PyPI working again

pyproject.toml
=> Create 0.6.0 release
