grid-parity-exchange/Egret

egret/data/model_data.py

This PR is for the unit commitment models, which right now expect the dictionary returned by ModelData.attributes() to have a 'names' key. As-is if there are no elements of element_type you get an empty dictionary--even if that element_type exists in the data dictionary but has no elements.
This change doesn't affect the OPF models--they still build/solve without complication (and identically). In the case of a particular element_type not being found, the for loop in ModelData.attributes() does nothing, so we get back a dictionary {'names' : [] }.

Modification to the behavior of ModelData.attributes

---

egret/model_library/transmission/tx_utils.py
egret/parsers/prescient_dat_parser.py

This is fix for issue #3.
Note that when the model_data dict gets dumped/loaded from json, dictionary keys are converted to strings. To keep things consistent, we need require that time_indices be strings, hence the update to the prescient_dat_parser.

Fix for json keys being strings

---

egret/model_library/transmission/tx_utils.py
egret/models/acopf.py
egret/models/dcopf.py
egret/models/economic_dispatch.py

New function in tx_utils that returns gens_in_service_by_bus. Created this function instead of requiring gen_attrs to be passed into the balancing constraints.

Should only balance generators that are 'in service'

---

egret/data/model_data.py
egret/model_library/transmission/tx_utils.py

Adds a method to ModelData, clone_in_service, to only clone elements which have non-False in_service flags. Elements without in_service flag are cloned.

Adding functionality to ignore out of service elements

---

setup.py

To maximize chances of a smooth install, I reactivated the dependency list in setup.py and modified it to include: 
- Pyomo >=5.6
- numpy (unsure if we need a specific version dependency)
- pytest
The last item might be mildly controversial. I decided to include this dependency so that users can quickly run some basic regression tests, making it easy to kick the tires on the new install.

Reactivating and updating dependencies in setup.py.

---

egret/parsers/rts_gmlc_parser.py
setup.py

This PR does the following:
1. Fixes issue #26 
1. Removes pandas deprecation warnings about read_table
1. Adds pandas as a requirement to setup.py because the rts_gmlc_parser uses it

Improvements to rts_gmlc_parser

---

egret/model_library/unit_commitment/power_balance.py

PowerOutputStorage was modified in the storage model to be the "grid side" output of the storage. This is reflected in the `power_balance` version of power flow (see line 308) but not in the _add_egret_power_flow version, likely due to a manual merge error.

Making _add_egret_power_flow consistent with the modified storage model

---

egret/model_library/transmission/tx_utils.py

A missing comma in the master dictionary was causing a few thermal generator attributes not to be scaled upon output.

Fix for model_data scaling

---

egret/parsers/parser.py

This is an implementation of a generic parser for input data that is similarly formatted to the RTS-GMLC/RTS_Data format.
* The module is based on the existing `egret/parsers/rts_gmlc_parser.py` module,
* Load time series are specified by bus analogously to how PV time series are specified by generator.
* Load time series are consequently specified for each bus in the time series pointer file.
* The parser for creating ModelDict/ModelData objects has been adjusted to support the above changes.
A conversion function for converting an RTS-GMLC/RTS_Data directory to this new format has been implemented. 
> Note: You will need to rename `RTS_Data/SourceData/timeseries_pointers.csv` to `RTS_Data/SourceData/timeseries_pointers_orig.csv`. This was implemented in such a way so that the original …

Implemented generic parser and converter for RTS-GMLC case

---

egret/parsers/rts_gmlc_parser.py

This closes issue #58.
Now that the UC model tracks heat rates explicitly, we need to be pulling the fuel cost out when parsing RTS-GMLC.

Adding fuel_cost to gen_dict

---

egret/model_library/unit_commitment/params.py
egret/model_library/unit_commitment/power_balance.py

When creating Egret-style networks for UC, we were using ModelData.clone_at_timestamp(). This is an expensive method, and was already currently unnecessary as most of the data is already pulled out of the ModelData object.
This PR removes the unnecessary call and also adds parameters for reference bus data so nothing in power_balance.py operates on ModelData objects.

UC network performance improvements

---

egret/common/lazy_ptdf_utils.py
egret/common/solver_interface.py
egret/data/data_utils.py
egret/model_library/transmission/branch.py
egret/model_library/transmission/bus.py
egret/model_library/unit_commitment/power_balance.py
egret/model_library/unit_commitment/uc_model_generator.py
egret/models/dcopf.py
egret/models/tests/test_unit_commitment.py
egret/models/unit_commitment.py

This PR makes several changes related to building and solving transmission models using PTDFs.
1. Putting more constant multiplications into numpy.
1. Creating a pyomo Var `p_nw` and associated Constraint for bus net withdraw. This moves the arithmetic for this into the solver.
1. Using `LinearExpression` for dense PTDF constraints.
1. Minimizing the work done between solver calls for lazy PTDF by only loading in needed variable values `p_nw` when using persistent solvers
1. Separating out the outer lazy PTDF solve loop in unit_commitment.py
1. Changing the logic of which PTDF constraints get added -- default now only adds one constraint (per time period) per iteration. Can be set with `max_violations_per_iteration` option.
1. Eliminating `lazy_rel_flow_tol` option and associated code.

Lazy PTDF Enhancements

---

egret/viz/generate_graphs.py

This PR makes changes to the stack graph generation module.
* Stack graph generation groups are now sorted deterministically according to module definitions. Previously, the order was determined by dictionary insertion order which was likely related to generator names. Now, the groups are sorted in a predetermined order before each stack is constructed. This order is (from bottom to top):
1) Nuclear
1) Coal
1) Hydro
1) Gas/NG
1) Oil
1) Synchronous Condenser
1) Wind
1) Solar/PV
1) Biomass
1) Geothermal
1) Battery
* The remaining components of the stacks such as renewable curtailment and load shed will remain ordered as previously. 
* This change also applies when individual generators are broken out discretely within each generation type grouping.
* An issue where certain generator/fuel …

Enforced sorting of stack graph components

---

egret/models/tests/test_unit_commitment.py
egret/models/unit_commitment.py

The unit commitment solver was not saving PTDF matrices when instructed to. This PR fixes that issue and enhances an existing test to ensure the file is serialized.

PTDF UC save fix

---

egret/common/lazy_ptdf_utils.py
egret/data/data_utils.py
egret/model_library/transmission/tx_calc.py
egret/models/tests/test_dcopf.py

This PR makes several modifications to the way PTDFs are calculated. The main changes are
1. Use of numpy.fromiter to avoid creating intermediate lists
1. Only calculating the mapping from bus name to bus index once
1. Using scipy spare matrices where the matrix will likely be or is sparse
1. Using numpy dense matrices where the matrix will likely be or is dense
1. Building needed intermediary matrices using `scipy.sparse.coo_matrix`, when sparse.
Limitations
1. The return types of the matrices from `tx_calc.calculate_ptdf` and `tx_calc.calculate_ptdf_ldf` now depend on if the option `sparse_index_set_branch` is set. If so, the returned matrices will be in a scipy sparse matrix format. If not, they will be numpy dense matrices.

[WIP] PTDF calculation performance improvements

---

README.md

Users should prefer `pip install -e .` instead of `python setup.py install` if they clone the repo.
1) Users can uninstall using `pip uninstall egret`. This works with `pip install .` or `pip install -e .`
2) If users are using egret in a package in a separate folder, and if they change a file, say `objective.py` in egret or do a git pull to get new changes, using `pip install -e .` will allow users to pick up the changes in the separate folder without rerunning `pip install .` or `python setup.py install`.

Prefer `pip install -e .` instead of `python setup.py install`

---

egret/models/dcopf.py
egret/models/unit_commitment.py

This PR makes two changes:
1. Fixes the termination logic for lazy PTDF UC when violations are present in the model. Currently, additional constraints may be added upon termination, which resets variable values when using a persistent solver.
1. Adds documentation for the DCOPF and UC lazy ptdf solver loops.

Fixing termination logic for lazy PTDF UC with violations

---

egret/model_library/unit_commitment/fuel_consumption.py

Fixes an issue where generators which are not dual fuel where causing model build issues for dual fuel generator parameters, if they had certain parameters set.
This PR uses the dual_fuel_attrs slice everywhere appropriate.

Using dual_fuel_attrs where appropriate

---

egret/model_library/unit_commitment/uc_model_generator.py
egret/models/unit_commitment.py

This PR moves where the ModelData object is copied and scaled so that `egret.model_library.unit_commitment.uc_model_generator.generate_model` can be called by users without necessitating calling other functions.

Making uc_model_generator.generate_model more user-friendly

---

egret/viz/generate_graphs.py

* Recognizing dual fuel generators (aux_fuel_capable == True) and stacking separately
* Indicating when aux fuel is in use
* TODO: Apply these enhancements for all display modes (show individual generators in stack components, show individual generators)
* Fixing an issue where the y-axis max limit was set to exactly the tallest stack's height. The y-axis max value is now 105% of the tallest stack's height.
The '-..' hatch pattern indicates the portion of generation from dual fuel generators that are operating using auxiliary fuel at the time. In other words, if a dual fuel generator at time t is consuming any aux. fuel, its contribution to the stack at time t will be hatched. The quickstart hatch pattern will augment this hatch pattern, if applicable.

[WIP] Stack graph generation enhancements

---

examples/unit_commitment/pglib_uc_example.py
examples/unit_commitment/test_uc_example.py

This PR adds and "examples" directory to the root and two unit commitment code examples, one using pglib-uc and another using a preexisting test problem. The unit commitment examples are in a "unit_commitment" subdirectory, with the thought we'd collect more such examples for different models.

UC examples

---

egret/model_library/unit_commitment/fuel_consumption.py
egret/model_library/unit_commitment/fuel_supply.py
egret/model_library/unit_commitment/params.py
egret/model_library/unit_commitment/services.py
egret/model_library/unit_commitment/tests/test_uc_utils.py
egret/model_library/unit_commitment/uc_utils.py

This PR makes changes to the way the unit commitment models use the `initialize` keyword argument of pyomo Param. Due to upstream changes in pyomo, the way it is currently held is no longer valid against pyomo master.
Specifically, the current behavior of Egret returns `None` when a value is not provided, which had caused pyomo to fall back on value provide by the `default` keyword arugment. Due to Pyomo/pyomo#1272, now values returned by the initializer function not in the domain cause pyomo to raise an exception.
The proposed behavior in the PR always gives a `dict` to the `initialize` argument of Param. Further, the way each dictionary is constructed preserves the sparsity for Params which are often at their default value.

Changes to unit commitment model for pyomo PR #1272

---

egret/model_library/unit_commitment/uc_utils.py

The changes the behavior of the high-level unit commitment model consistency checker to only issue warnings instead of Exceptions.
Users who wish to construct a full unit commitment model from model_library should be using `egret.model_library.unit_commitment.uc_model_generator.generate_model`, which enforces this consistencies, instead of calling the other modules in egret.model_library.unit_commitment.
This frees the other modules in `egret.model_library.unit_commitment` to be used only partially or in other ways, provided the user attaches the correct objects to the underlying pyomo model.

Demoting Exceptions in add_model_attr to warnings

---

egret/model_library/unit_commitment/production_costs.py
egret/model_library/unit_commitment/ramping_limits.py
egret/model_library/unit_commitment/services.py
egret/model_library/unit_commitment/startup_costs.py
egret/model_library/unit_commitment/thermal_convex_hull.py
egret/models/tests/test_unit_commitment.py
egret/models/unit_commitment.py

This PR adds some convex hull formulations for individual generators that had been previously absent in Egret and associated constraint/model builders.
It also fixes the docstrings on create_* functions in unit_commitment.py.

Convex hull formulations

---

egret/model_library/unit_commitment/params.py

Prevents a deprecation warning from being printed due to upstream changes in Pyomo (Pyomo/pyomo/pull/1266) and is also more explicit.

Making BusFrom/BusTo Param domains explicit for unit commitment model

---

egret/common/tests/test_log.py

temporarily, until we can diagnose their failure on Travis.

Disabling logging tests

---

egret/models/tests/test_unit_commitment.py
egret/models/unit_commitment.py

`create_CHP_unit_commitment_model` and `create_super_tight_unit_commitment_model` inadvertently create relaxed models by default. This PR changes both to create integer restricted models by default, which is the norm for every other `create_*_unit_commitment_model` in this file.
Because Travis/CBC sometimes have issue with `test_CHP_uc_model`, this also marks that test to only run if `comm_mip_avail`.

Changing default to relaxed=False for all UC model generators

---

egret/data/ptdf_utils.py
egret/model_library/unit_commitment/power_balance.py
egret/model_library/unit_commitment/uc_model_generator.py

In support of: https://github.com/grid-parity-exchange/Prescient/issues/28

Adding a hook so a user can specify an in-memory PTDF matrix when creating a unit commitment model

---

README.md
setup.py

This change would make Pyomo 5.7 or later a requirement for EGRET.
Pyomo versions less than 5.7 have issues processing LinearExpressions in some cases (see https://github.com/Pyomo/pyomo/pull/1403, https://github.com/Pyomo/pyomo/pull/1405). The Prescient regression tests fail with #143 and Pyomo<5.7, so unless we revert #143 this is already a soft requirement. And it goes without saying that LinearExpressions were used in limited places before #143, hence making this change prudent regardless of #143.

Updating requirements to Pyomo 5.7

---

egret/models/ac_relaxations.py
egret/models/acopf.py

Addresses #162 - but only for AC models at the moment. If this works / is accepted, then I'll quickly extend/mirror in DC and DC with losses model builders.
This PR takes the position that (1) penalties on real and reactive power balance slack variables *must* be intentionally and carefully set by a user and (2) only marginal penalty factors will be supported (no multipliers on internally computed factors).
Users must specify values in the model-data dictionary, e.g., as follows:
md_dict = create_ModelData(path_to_data)
md_dict.data["system"]["load_mismatch_cost"] = 10000      # $/MW
md_dict.data["system"]["q_load_mismatch_cost"] = 10000  # $/MW    
This significantly improves consistency with unit commitment model builders.

Re-working feasibility slack penalty factor handling in AC model builders. 

---

egret/model_library/unit_commitment/params.py

This used to be used by Prescient, and got carried over. The UC models currently do nothing with this Param.
This PR also sneaks in a bug fix -- UnitOnT0 is incorrectly determined for generators on less than one hour.

Removing unused FailureProbability Param

---

egret/model_library/transmission/tx_utils.py
egret/model_library/unit_commitment/power_balance.py
egret/models/acopf.py
egret/models/copperplate_dispatch.py
egret/models/dcopf.py
egret/models/dcopf_losses.py

Would close #164. The computed slack bounds are similar to those in the [unit commitment code](https://github.com/grid-parity-exchange/Egret/blob/bd2fe978016eddb2f87db93b2ae5012e50bf6600/egret/model_library/unit_commitment/power_balance.py#L383).
@DLWoodruff, would you mind trying this out?
Is 0 the right value to initialize all these slacks to?

OPF slack bounds

---

egret/model_library/unit_commitment/params.py
egret/parsers/prescient_dat_parser.py
egret/viz/generate_graphs.py

For certain *.dat files, like those included with mpi-sppy, the "QuickStart" attribute was not properly carried through from dat file to Egret ModelData object to Pyomo unit commitment model.
This PR makes some minor changes to the prescient_dat_parser and the unit commitment parameter loader. Note that `quickstart_capable` is not used anywhere else -- but `fast_start` gets used for unit which can provide 10-minute reserve. `supplemental_start` is used for units which can provide 30-minute reserve.

Properly propogating the QuickStart attribute for prescient dat files

---

README.md
egret/common/lazy_ptdf_utils.py
egret/model_library/transmission/branch.py
egret/model_library/transmission/tx_calc.py
egret/model_library/unit_commitment/power_balance.py
egret/model_library/unit_commitment/thermal_convex_hull.py
egret/models/unit_commitment.py
setup.py

This PR makes two changes in anticipation of resolving #149.
1. For lazy constraints, slacks are now generated on-the-fly based on the `add_column` method for `PersistentSolver` (Pyomo/pyomo#1568). The current approach is okay for O(|L|) constraints (creating all slack variables up front), but something different will be needed for O(|L|^2) constraints. This change makes EGRET dependent on Pyomo 5.7.1+.
1. Minor clean-up in tx_calc for separate A, B_d matrices
1. Closes #182 
Limitations:
1. If the unit commitment problem is part of a larger block, and a persistent solver is used, the current implementation of lazy PTDF will raise a `RuntimeError`. I think this is manageable for the time being.

Lazy slacks

---

egret/models/unit_commitment.py

This would address https://github.com/grid-parity-exchange/Prescient/issues/77, which I think Egret should enforce on the output (that binary variables are in fact binary).

Rounding should-be binary values

---

egret/models/unit_commitment.py

The Pyomo dual suffix will always be on the top-level model. When the `relaxed` flag is `True`, this PR ensures we use the `dual` attribute on the top-level model, in case `m` is not the top-level model.

Using dual suffix on top-level model in _save_uc_results

---

egret/model_library/unit_commitment/params.py

In #15, I made a copy-paste error when writing this error message. This PR corrects that.

Fixing wrong variable in error message

---

egret/data/data_utils.py
egret/data/model_data.py
egret/data/tests/test_model_data.py
egret/models/tests/test_unit_commitment.py

Changes `ModelData.__init__` to do some basic type-checking on the input and allows for passing in another `ModelData` object or a path which should load the data.
These changes are mostly for convenience, but not allowing arbitrary objects to be set on `ModelData.data` also provides some type-safety.
Other changes: the unit commitment test are changed to use this new functionality.

Making ModelData.__init__ more useful

---

.github/workflows/prescient.yml
egret/models/unit_commitment.py

This PR simply refactors the 100-line function which controls a lazy-ptdf pass to call several new functions for its main components to make the existing functionality more modular.
Bigger question: there's now ~300 lines of lazy PTDF logic in unit_commitment.py that should probably be in its own file, and probably be further refactored. There's also the function `_lazy_ptdf_dcopf_solve_loop` in dcopf.py and the files `egret/common/lazy_ptdf_utils.py` and the file `egret/data/ptdf_utils.py`. 
Should we organize Egret's PTDF functionality into its own (top-level) directory?
Also makes some unrelated changes to the Prescient CI tests because Prescient's dependencies are not currently reliably installed via pip https://github.com/grid-parity-exchange/Prescient/pull/92.

Refactoring _lazy_ptdf_uc_solve_loop into component functions

---

egret/parsers/rts_gmlc/__init__.py

PR #209 was missing an `__init__.py` file in the new directory it added. This PR adds an empty `__init__.py` file to address that.

adding missing __init__ file

---

egret/parsers/rts_gmlc/_reserves.py
egret/parsers/rts_gmlc/parsed_cache.py
egret/parsers/rts_gmlc/parser.py

Use the Reserve_Products row of simulation_objects.csv to decide which scalar reserve products to included in a model.
Note that this only applies to scalar reserve requirements (the ones listed in reserves.csv). It does not filter timeseries by reserve type; if a timeseries is listed in timeseries_pointers.csv for a given reserve, the timeseries is included in the model
even if the reserve type isn't listed in simulation_objects.csv.
If simulation_objects.csv does not have a Reserve_Products row then all scalar reserve products are accepted for both DAY_AHEAD and REAL_TIME models.
To summarize:
* If a reserve product has a timeseries for the relevant simulation type, the timeseries will be included.
* If a reserve product does not have a timeseries but does have a row in reserves.csv, …

Filter scalar reserve requirements

---

egret/common/lazy_ptdf_utils.py

`IndexedComponent.itervalues()` was deprecated in Pyomo 6; this PR eliminates calls to it from Egret. I believe this implementation should have the same performance on older versions of Pyomo, while bypassing creating an itermediate list like the `value` method does in older (and current) versions of Pyomo.
One incongruity I caught in current Pyomo: the `keys()`, `values()`, and `items()` methods on `IndexedComponent` document returning an _iterator_, but instead return a _list_.

Eliminating Pyomo 6 deprecation warning

---

egret/model_library/transmission/gen.py
egret/model_library/transmission/tests/test_tx_utils.py
egret/model_library/transmission/tx_utils.py
egret/model_library/unit_commitment/params.py
egret/models/acopf.py
egret/models/copperplate_dispatch.py
egret/models/dcopf.py
egret/models/dcopf_losses.py
egret/models/scopf.py
egret/models/tests/test_acopf.py
egret/models/tests/test_dcopf.py

Support for piecewise (convex) costs in ACOPF

Support for piecewise (convex) costs in ACOPF

---

egret/model_library/transmission/tests/test_tx_utils.py
egret/model_library/transmission/tx_utils.py

Follow up to #227. Closes #235.
Additional logic does better handling of extending piecewise cost curves above or below their original specification. We now raise a single warning if we extend the piecewise cost curve for some generator.

Catching more edgecases in piecewise logic

---

egret/models/unit_commitment.py

...for lazy PTDFs in unit commitment.

Adding reset after pre-lp warmstart loop

---

egret/model_library/transmission/gen.py
egret/model_library/transmission/tests/test_tx_utils.py
egret/model_library/transmission/tx_utils.py

Deal with single-point cost curves as a special case.

Singlecost

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR adds a Pull Request Template (derived from Pyomo's) and cleans up the markdown formatting in the README.
- Add (this) PR template
- Clean up markdown formatting so the README renders correctly on GitHub

Add a PR template, update README formatting

---

.github/workflows/egret.yml
.github/workflows/prescient.yml
README.md
egret/model_library/unit_commitment/power_vars.py
egret/model_library/unit_commitment/startup_costs.py
setup.py

Pyomo 6.1 deprecated `__getitem__()` for ordered Pyomo Sets
- Replace all instances of `__getitem__` with `at` for ordered Pyomo Sets. 
- Bump minimum Pyomo version to 6.1.2.

Replacing __getitem__() with at() for ordered sets

---

egret/model_library/unit_commitment/params.py

#243 missed an instance of SetData.__getitem__()
- Replace `__getitem__` with `at` in egret/model_library/unit_commitment/param.py
- Minor cleanup of these validators.

Replacing __getitem__() with at() for ordered sets, Part II

---

egret/parsers/rts_gmlc/parsed_cache.py

The RTS-GMLC parser references a particular DataFrame cell by row key where it should reference by row position. The test didn't catch this because the first row of the data frame has a key of 0 in the RTS-GMLC data we test against. That isn't guaranteed to the case in other data sets.
- Fix indexing
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission …

Fix DataFrame indexing error in RTS-GMLC parser

---

egret/common/lazy_ptdf_utils.py
egret/model_library/unit_commitment/services.py

Updates for objective function mutability, driven by https://github.com/grid-parity-exchange/Prescient/issues/110
- Make reserve penalty Parameters mutable
- Fix bug in the lazy objective function, which wasn't respecting the mutability of `SystemContingencyLimitPenalty`
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant …

Updating mutable penalty params

---

egret/model_library/unit_commitment/services.py

I want a list of ancillary service names that external code (Prescient) can use
- Expose the list of ancillary service names

Expose list of ancillary service names

---

setup.py

This is what `setuptools` ends up calling this version anyways:
```
~/.local/lib/python3.7/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '0.5.2-dev' to '0.5.2.dev0'
```
- Change version from `0.5.2-dev` to `0.5.2.dev0`.
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf …

Using python standard version names

---

egret/models/acopf.py
egret/models/tests/test_acopf.py
egret/models/tests/transmission_test_instances/test_instances/delta_theta_bounds_0.m
egret/models/tests/transmission_test_instances/test_instances/delta_theta_bounds_10_to_20.m
egret/models/tests/transmission_test_instances/test_instances/delta_theta_bounds_minus_10_to_10.m

The computation of bounds for the auxiliary variables `c = v_f * v_t * cos(dt)` and `s = vf * vt * sin(dt)` had bugs. This PR uses interval arithmetic to improve the robustness of these computations and adds tests.

more robust handling of voltage angle difference limits

---

egret/viz/generate_graphs.py

Only set `'AGG'` matplotlib backend if Python isn't launched in interactive mode. As-is, sometimes you cannot generate graphs in jupyter notebooks if Egret's graph generation code has been imported.
-
-

Enabling interactive graphics

---

.github/workflows/egret.yml
README.md
egret/model_library/transmission/tx_utils.py
egret/models/ac_relaxations.py
egret/models/acopf.py
egret/models/dcopf.py
egret/models/tests/test_acopf.py
egret/models/tests/test_dcopf.py
setup.py

This PR adds an option to the ACOPF and DCOPF models to construct variables corresponding to out-of-service generators and transmission lines.

option to keep variables for out of service elements

---

egret/parsers/rts_gmlc/parser.py

A project that uses Egret has requested this feature
- When parsing files in GMLC format, read DC branch information.

Include DC branches when reading GMLC-formatted csv files

---

egret/parsers/rts_gmlc/parser.py

When parsing RTS-GMLC csv files, if area names were numeric (such as an area named "1"), then some places in the RTS-GMLC parser read the area names as strings and other places read the names as numbers. This caused time series data for areas to not be associated with the correct area.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make …

Ensure area names are read as strings in RTS-GMLC, even if numeric

---

.github/workflows/prescient.yml
egret/parsers/rts_gmlc/parser.py
setup.py

Fixes an error when using Pandas 1.5 or later. Pandas started converting Series objects into bare numpy arrays when assigning to a cell.
- When reading RTS-GMLC csv data, use a different method to store Series objects in DataFrame cells.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of …

Make egret compatible with pandas 1.5

---

egret/parsers/rts_gmlc/parser.py

Fixes reading dates from the 2D version of timeseries files (an example is at https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/timeseries_data_files/Reserves/DAY_AHEAD_regional_Flex_Down.csv). Previous pull request only handled the columnar timeseries CSV format.
Keep up with changes in pandas 2.0.
-
-
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received …

Fix date handling for 2D timeseries CSV layout

---

.github/workflows/egret.yml
egret/model_library/transmission/branch.py
egret/model_library/unit_commitment/uc_utils.py

remove Pyomo deprecation warnings
